Обертка для базы данных + немного ручки Sing-In
rep-co/fablescope-backend pull request #10
Opened 2024-03-19 03:08 UTC by sheeiavellie

Частично написал обертку для базы и ручку Sing-In'а. Также добавил штук чтобы протестить. Ничего не работает, ничего не понятно.

2024-03-21 10:51 UTC, tplaymeow requested changes

2024-03-21 10:51 UTC, tplaymeow commented on wardrobe-auth/cmd/api/main.go
> +
?

2024-03-21 10:51 UTC, tplaymeow commented on wardrobe-auth/database/ydb.go
> +	token := "t1.9euelZrOk5SczomLypOXlImOlImLle3rnpWaiZCLzM-eipuXkZvPy5mOx5Hl8_cTGhxQ-e9nQHhh_N3z91NIGVD572dAeGH8zef1656Vmp6cnpeUiciJkMiQmpGJyIzH7_zF656Vmp6cnpeUiciJkMiQmpGJyIzH.AvLrBtEmKuEtJXONEcEGhNaa
Не хардкодь креды

2024-03-21 10:51 UTC, tplaymeow commented on wardrobe-auth/database/ydb.go
> +	token := "t1.9euelZqZnorOnJ2ayJiOnImKz8_Pj-3rnpWaiZCLzM-eipuXkZvPy5mOx5Hl8_cbGBNQ-e8vEDBB_N3z91tGEFD57y8QMEH8zef1656VmpjPmZaWjpGdipjInZiJxs-W7_zF656VmpjPmZaWjpGdipjInZiJxs-W.LEnGtHihEVBn2AJhHO6EteS6
Не хардкодь креды

2024-03-21 10:51 UTC, tplaymeow commented on wardrobe-auth/handlers/auth.go
> +	r *http.Request,
?

2024-03-21 10:51 UTC, tplaymeow commented on wardrobe-auth/handlers/auth.go
> +	r *http.Request,
?

2024-03-21 10:51 UTC, tplaymeow commented on wardrobe-auth/middlewares/auth.go
> +	}
Что здесь происходит? Мы должны валидировать jwt

2024-03-21 15:52 UTC, sheeiavellie commented on wardrobe-auth/cmd/api/main.go
> +
outdated

2024-03-21 16:09 UTC, sheeiavellie commented on wardrobe-auth/middlewares/auth.go
> +	}
Тут мы проверяем, не пришел ли какой-нибудь мусор. Эта реюзабл штука, ее можно будет вставить во все. Сразу скажу, что пока она кушает только аккаунт реквест (это нужно для SingUp и SingIn), но потом можно будет просто накатить интерфейс и кушать любой реквест (в том числе и рефреш токен). А что касается валидации jwt, то это вообще не на этом серве делается, этот серв просто выдает и учитывает из и пользователей. Валидировать jwt будем на Cloud Functions, обсуждали же это.

2024-03-22 00:09 UTC, sheeiavellie commented on wardrobe-auth/handlers/auth.go
> +	r *http.Request,
fixed

2024-03-22 00:10 UTC, sheeiavellie commented on wardrobe-auth/handlers/auth.go
> +	r *http.Request,
fixed

2024-03-22 01:41 UTC, tplaymeow commented on wardrobe-auth/middlewares/auth.go
> +		// 2. Add JWT to JWT db
Зачем jwt добавлять в бд?

2024-03-22 09:30 UTC, sheeiavellie commented on wardrobe-auth/middlewares/auth.go
> +		// 2. Add JWT to JWT db
Можно не добавлять. Но вообще, это чтобы вести учет токенов, иметь возможность отзывать их

2024-03-22 13:24 UTC, tplaymeow approved these changes

2024-03-23 00:11 UTC, merged