SingUp and SingIn middlewares
rep-co/fablescope-backend pull request #12
Opened 2024-03-28 09:17 UTC by sheeiavellie

Полностью готова ручка создания аккаунта. На уровне запроса и получения ответа готова ручка входа в аккаунт (там нужно реализовать рефреш сессии).

2024-03-28 16:29 UTC, tplaymeow requested changes

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/cmd/api/main.go
> +	tokenService := services.NewTokenService([]byte("amogus"))
Нельзя комитить секреты

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/data/token.go
> +	JWTToken     string `json:"jwt_token"`
Странное название. JWT... не описывает назначение этого токена, а лишь указывает на его формат
```suggestion
	AccessToken     string `json:"access_token"`
```

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/data/token.go
> +	RefreshToken string `json:"refresh_token_id"`
Что за id? Я бы не добавлял это в контракт
```suggestion
	RefreshToken string `json:"refresh_token"`
```

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/database/ydb.go
> +				options.WithPrimaryKeyColumn("email"),
Может тогда удалим account_id? Или оно в каких-то запросах нужно будет? Я не настаиваю, если что

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/database/ydb.go
> +        INSERT INTO account (account_id, name, email, password)
Тут бы еще уметь отличать на клиенте ситуацию, когда такой пользователь уже существует

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/database/ydb.go
> +			// TODO: refactor this. Research more about transaction errros
> Тут бы еще уметь отличать на клиенте ситуацию, когда такой пользователь уже существует

Вот это надо бы поресерчить

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/handlers/auth.go
> +		log.Printf("An error occured at HandleSignUp: %v.", err)
```suggestion
		log.Printf("An error occured at HandleSignIp: %v.", err)
```

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/handlers/auth.go
> +		log.Printf("An error occured at HandleSignUp: %v.", err)
```suggestion
		log.Printf("An error occured at HandleSignIp: %v.", err)
```

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/middlewares/auth.go
> +				http.Error(w, "An account with the given email already exists", http.StatusConflict)
Это не совсем правда)

2024-03-28 16:29 UTC, tplaymeow commented on wardrobe-auth/services/token.go
> +	refreshToken := uuid.New().String()
Норм, но при рефреше учитывай, что с маленькой вероятностью, но UUID имеет коллизии

2024-03-29 06:06 UTC, sheeiavellie commented on wardrobe-auth/services/token.go
> +	refreshToken := uuid.New().String()
Можно генерировать два UUID и конкатенировать их
))

2024-03-29 06:07 UTC, sheeiavellie commented on wardrobe-auth/middlewares/auth.go
> +				http.Error(w, "An account with the given email already exists", http.StatusConflict)
))

2024-03-29 06:17 UTC, sheeiavellie commented on wardrobe-auth/database/ydb.go
> +				options.WithPrimaryKeyColumn("email"),
Пускай будет. Можно будет записывать в рефреш сессии, чтобы понимать, что две разные сессии открыты для одного аккаунта.

2024-03-29 16:38 UTC, sheeiavellie commented on wardrobe-auth/database/ydb.go
> +        INSERT INTO account (account_id, name, email, password)
А как это на клиенте делать-то? Опиши идею

2024-03-29 16:46 UTC, tplaymeow commented on wardrobe-auth/data/token.go
> +	JWTToken     string `json:"access_token"`
```suggestion
	AccessToken     string `json:"access_token"`
```

2024-03-29 16:46 UTC, tplaymeow commented on wardrobe-auth/database/ydb.go
> +        INSERT INTO account (account_id, name, email, password)
Имею ввиду чтоб бык возвращал какую-то информацию, по которой можно было понять что такой пользователь существует

2024-03-29 16:47 UTC, tplaymeow commented on wardrobe-auth/services/token.go
> +	refreshToken := uuid.New().String()
нет смысла

2024-03-30 06:20 UTC, sheeiavellie commented on wardrobe-auth/database/ydb.go
> +        INSERT INTO account (account_id, name, email, password)
А в каком виде это должно быть? Формально, 409-й код это тоже информация о том, что пользователь уже есть.

2024-03-30 06:26 UTC, sheeiavellie commented on wardrobe-auth/services/token.go
> +	refreshToken := uuid.New().String()
Так ли важны коллизии как таковые? Ну т.е. рефреш токен то будет в любом случае захэширован в сессии.

2024-03-30 20:08 UTC, tplaymeow approved these changes

2024-03-31 08:26 UTC, merged