feature/form-endpoint
rep-co/fablescope-backend pull request #3
Opened 2023-12-28 18:50 UTC by sheeiavellie

Implement form/category endpoint

2023-12-28 20:28 UTC, tplaymeow requested changes

2023-12-28 20:28 UTC, tplaymeow commented on storyteller-api/data/category.go
> +	SvgString   string `json:"svg_string"`
`SvgString` - плохое имя. Название поля должно отражать его смысл в этой модельке

2023-12-28 20:28 UTC, tplaymeow commented on storyteller-api/handlers/category.go
> +	}
В случае ошибке сервер должен вернуть ошибочный HTTP код

2023-12-28 20:28 UTC, tplaymeow commented on storyteller-api/util/util.go
> +func WriteJSON(w http.ResponseWriter, status int, v any) error {
А error как-то используется?

2023-12-28 20:28 UTC, tplaymeow commented on storyteller-api/handlers/index.go
> +	}
В случае ошибке сервер должен вернуть ошибочный HTTP код. Плохо игнорировать ошибки

2023-12-28 23:14 UTC, sheeiavellie commented on storyteller-api/data/category.go
> +	SvgString   string `json:"svg_string"`
Пофиксил в [1f7f535](https://github.com/rep-co/fablescope-backend/pull/3/commits/1f7f53580224e12f46e5a14a1aa739212fc84be8)

2023-12-28 23:16 UTC, sheeiavellie commented on storyteller-api/util/util.go
> +func WriteJSON(w http.ResponseWriter, status int, v any) error {
Error нужен, т.к. json может плохо заинкодиться в ```json.NewEncoder(w).Encode(v)```, эта функция возвращает ошибку так или иначе, так что ее нельзя игнорировать.

2023-12-28 23:37 UTC, sheeiavellie commented on storyteller-api/handlers/category.go
> +	}
Пофиксил в https://github.com/rep-co/fablescope-backend/pull/3/commits/2990af347ff8bef82a5e52f61284fb64748b0a08

2023-12-28 23:43 UTC, sheeiavellie commented on storyteller-api/handlers/index.go
> +	}
Пофиксил в https://github.com/rep-co/fablescope-backend/pull/3/commits/add6157b85fbe53856239eb4a09f43bbfd0698e8

2023-12-29 07:34 UTC, tplaymeow commented on README.md
Интересный вопрос. Почему `make run` сам не делает `make build`? Можно через зависимости реализовать

```
build
    ...
run: build
    ...
```

2023-12-29 07:34 UTC, tplaymeow commented on README.md
Может ssh ссылку вставить?
git@github.com:rep-co/fablescope-backend.git

2023-12-29 07:34 UTC, tplaymeow commented on README.md
Может для шага 3 добавим комманду `cd fablescope-backend`?

2023-12-29 07:35 UTC, tplaymeow approved these changes

2023-12-30 01:00 UTC, sheeiavellie commented on README.md
Не вижу особого смысла, репа паблик

2023-12-30 01:06 UTC, tplaymeow commented on README.md
Additional, Run server. А может Build server?

2023-12-30 01:09 UTC, sheeiavellie commented on README.md
Переделал, я немного невнимательный

2023-12-30 01:09 UTC, merged