feature/generate-endpoint
rep-co/fablescope-backend pull request #4
Opened 2024-02-06 00:24 UTC by sheeiavellie

НЕ ВЛИВАТЬ ЭТОТ ПР (пока что)Запилил базу под эндпоинт генерации сказки.

2024-02-17 09:19 UTC, tplaymeow requested changes

2024-02-17 09:19 UTC, tplaymeow commented on storyteller-api/cmd/api/main.go
> +	router.GET(
Логичнее сделать пост ручку и передавать массив в теле. Согласен? Не?

2024-02-17 09:19 UTC, tplaymeow commented on storyteller-api/storygenerator/openai.go
> +	defer s.mu.Unlock()
Зачем?

2024-02-18 03:35 UTC, sheeiavellie commented on storyteller-api/cmd/api/main.go
> +	router.GET(
Не согласен, т.к. POST подразумевает хранение данных, иными словами, если ты шлешь данные постом, то это те данные, которые нужно сохранить. В данном случае мы не делаем этого, мы буквально хотим получить данные от серва (сгенеренную историю), а теги это способ повлиять на данные. Я допускаю, что в будущем можно было бы поделить это на POST запрос, который генерирует историю по тегам, а потом просто делать GET по ID, но в данный момент мы нигде не храним историю, и не понятно, нужен ли такой функционал вообще.

2024-02-18 03:36 UTC, sheeiavellie commented on storyteller-api/storygenerator/openai.go
> +	defer s.mu.Unlock()
Так было в туториале)) Это можно убрать в целом, но пусть пока будет, эта штука делает функцию горутин сейв вроде

2024-02-18 06:33 UTC, tplaymeow commented on storyteller-api/cmd/api/main.go
> +	router.GET(
Но отправка заполненной формы GET методом выглядит также странно. Например, в вебе всегда форма отправлялась POST методом

2024-02-18 10:46 UTC, sheeiavellie commented on storyteller-api/cmd/api/main.go
> +	router.GET(
Возможно это так, если воспринимать выбор тегов как заполнение формы. Однако, подобный взгляд кажется мне неверным, теги это не данные, которые будут затем сохранены, это скорее что-то вроде пагинации. Более того, даже если предположить, что это форма, и что она по этой (стоит отметить, весьма эзотерической) причине обязательно должна поститься, мы придем к ситуации, когда по сути у серва появится стейт (мы постим выбранные теги -> тем самым изменяем стейт). После поста тегов уже на основе этого стейта будет генерится история. Не кажется ли тебе такой подход не просто переусложненным, а откровенно говоря глупым? Резюмируя, я считаю, что теги это не форма, а просто констрейнт для генератора сказако, дополнительная деталь, которая влияет на то, что получит пользователь (иными словами, для меня они как параметры в гугл мапс: коорды центра экрана и размер зума), при этом, мы избегаем ненужной комплексности.

2024-02-20 12:27 UTC, tplaymeow requested changes

2024-02-20 12:27 UTC, tplaymeow commented on storyteller-api/util/util.go
> +	w.WriteHeader(status)
Чо а зачем это?

2024-02-20 12:27 UTC, tplaymeow commented on storyteller-api/util/util.go
> +}
А нельзя без этой магии пихнуть теги в gpt?

2024-02-20 12:27 UTC, tplaymeow approved these changes

2024-02-20 13:34 UTC, sheeiavellie commented on storyteller-api/util/util.go
> +	w.WriteHeader(status)
Пофикшено, действительно, смысла в этом особого не было. Однако, дополнительно в будущем нужно будет подумать надо нормальным ответам на POST запрос (там ссылка должна быть по хорошему)

2024-02-20 13:37 UTC, sheeiavellie commented on storyteller-api/util/util.go
> +}
Ну теги засовываются как строка (они и промпт соединяются), так что в любом случае надо их в строку засунуть. Тут нет магии так-то, просто хелпер, чтобы объединить поля слайса структуры по их названию. Плюс, метод должен отрабатывать быстро, тут нечему тормозить. Можно было бы конечно написать метод, который бы конвертировал слайс из структур в строку без рефлекшин, но потом надо будет писать еще один такой, а потом еще. Лучше пусть будет реюзабл тема

2024-02-20 13:55 UTC, tplaymeow commented on storyteller-api/util/util.go
> +}
Почему просто не сделать что-то типа tags.map(e => e.name).join(", ")?
Зачем тут рефлексия?

2024-02-20 13:56 UTC, tplaymeow commented on storyteller-api/util/util.go
> +}
Также хочу отметить что рефлексия работает медленно и не безопасна

2024-02-20 15:12 UTC, sheeiavellie commented on storyteller-api/util/util.go
> +}
отробпайкнуто

2024-02-20 15:13 UTC, tplaymeow approved these changes

2024-02-20 15:14 UTC, merged